# Generated by Django 5.2.4 on 2025-07-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_remove_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
