# Generated by Django 5.2.4 on 2025-07-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_alter_book_author_bookcategory_description_and_more'),
    ]

    operations = [
    ]
