# Generated by Django 5.2.4 on 2025-07-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_auto_20250726_1616'),
    ]

    operations = [
    ]
