# Generated by Django 5.2.4 on 2025-07-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_auto_20250726_1617'),
    ]

    operations = [
    ]
