# Generated by Django 5.2.4 on 2025-07-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0007_auto_20250726_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
