# Generated by Django 5.2.4 on 2025-07-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_remove_book_author'),
    ]

    operations = [
    ]
