# Generated by Django 5.2.4 on 2025-07-26 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_auto_20250726_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='description',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Select the categories this author writes in', related_name='authors', to='bookshop.bookcategory')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshop.author'),
        ),
    ]
