# Generated by Django 5.2.4 on 2025-07-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0010_remove_bookcategory_description_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
