# Generated by Django 5.2.4 on 2025-07-13 12:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_img', models.ImageField(default='restaurant_default.jpg', upload_to='restaurant_images')),
                ('story', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Story')),
            ],
        ),
    ]
