# Generated by Django 5.2.4 on 2025-07-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_author_videocategory_video_author_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
    ]
