# Generated by Django 5.2.4 on 2025-07-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_author_bio_remove_author_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
