# Generated by Django 5.2.4 on 2025-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Untitled Video', max_length=200),
        ),
    ]
